Add integration tests for Nodegroups and Addons
aws-controllers-k8s/eks-controller pull request #13
Opened 2022-01-03 23:12 UTC by RedbackThomson

Description of changes:
Add create/delete tests for Nodegroup and Addon types

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

2022-01-04 01:22 UTC, RedbackThomson commented
/test eks-kind-e2e

2022-01-04 13:42 UTC, jaypipes requested changes
Let's have the runtime version update changes in a separate PR please, thank you @RedbackThomson!

2022-01-04 13:42 UTC, jaypipes commented on go.local.mod
> +	github.com/aws-controllers-k8s/runtime v0.15.2
I believe you should add this change in a separate commit/PR.

2022-01-04 19:56 UTC, RedbackThomson commented
> Let's have the runtime version update changes in a separate PR please, thank you @RedbackThomson!

It's just for the local Go mod file. It had a version mismatch compared to the "real" Go mod.

2022-01-04 20:06 UTC, jaypipes commented
> > Let's have the runtime version update changes in a separate PR please, thank you @RedbackThomson!
> 
> It's just for the local Go mod file. It had a version mismatch compared to the "real" Go mod.

Apologies, I missed that it was the local mod files...

2022-01-04 20:07 UTC, jaypipes approved these changes
:+1:

2022-01-04 20:08 UTC, jaypipes commented
@RedbackThomson are the test failures just a timeout issue?

2022-01-04 20:14 UTC, RedbackThomson commented
> @RedbackThomson are the test failures just a timeout issue?

Not exactly sure what I'm seeing here. I had multiple successful test runs in my local account. 

From the tests for `Nodegroup`:
```
Waiter encountered a terminal failure state: For expression "nodegroup.status" we matched expected path: "CREATE_FAILED"
```
Seems to imply that our node groups are failing to create?

From the tests for `Cluster`:
```
Cluster 'simple-cluster-mk8ub3sbxwegxqzj4' was not deleted from EKS
```
This test has been running for weeks without seeing problems, so don't see why we would have an issue here either.

2022-01-04 20:16 UTC, RedbackThomson commented
/test eks-kind-e2e

2022-01-05 00:26 UTC, vijtrip2 commented
/lgtm

2022-01-05 00:26 UTC, merged